### ISSUE TITLE
Graph can fail to render due to a divide by zero error during rendering

### ISSUE THREAD

**Issue by Hydrox6** [yuh25/Ping-Grapher#6]
```
2021-08-21 15:32:12 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.ArithmeticException: / by zero
	at com.pinggraph.PingGraphOverlay$1.render(PingGraphOverlay.java:129)
	at net.runelite.client.ui.overlay.components.PanelComponent.render(PanelComponent.java:131)
	at com.pinggraph.PingGraphOverlay.render(PingGraphOverlay.java:179)
```
(extra unneeded frames omitted for brevity)

It seemingly is to do with the calculation of `(maxPing - minPing) + 1`

**Comment by yuh25** [comment]
Should be fixed with the latest update
